### ISSUE TITLE
Patient list in Figure 3A

### ISSUE THREAD

**Issue by Kevin-Moo** [TheJacksonLaboratory/GLASS#153]
Dear Floris,

Thank you very much for making the code and data of the GLASS project open! It is a really exciting and important endeavor.

I am trying to reproduce Figure 3A from the open data, and I encountered some problems when selecting the patients. I wonder if it is possible for you to provide the ordered list of patients in Figure 3A. Thanks!

Best regards,
Quanhua Mu

PhD student
Hong Kong University of Science and Technology

**Comment by fpbarthel** [comment]
Dear Kevin,

Thank you for your interest and my apologies for the late reply. The figure is roughly sorted by the number of drivers per patient. I cannot provide you with an exact list of patients, but I can refer you to the R code that was used to generate the figures here https://github.com/TheJacksonLaboratory/GLASS/blob/master/R/figures/F1-F3-GLASS-heatmap.R. This R code references SQL queries that were used to build the input data tables and these were subsequently sorted in R. I hope that this helps.

Best regards,
Floris
