### ISSUE TITLE
Tables under ref. patch are not on Synapse

### ISSUE THREAD

**Issue by keremw** [TheJacksonLaboratory/GLASS#155]
Hi,
Thank you for your great work.
I've tried to download the tables from Synapse and apply the code in F1-F3-GLASS-heatmap.R heatmap_snv.sql on them. When I try the patch of ref. is missing from the tables. Specifically there seems to be a column named has_mut that is not present in any of the Synapse tables. Where can I find this column?
Thank you in advance,
Kerem

**Comment by fpbarthel** [comment]
Thank you for your interest. The `ref.driver_genes` table is a table with the genes listed in figure 3. The columns `has_cnv` and `has_mut` indicate whether they should be included in the list of mutations, list of copy number changes or both.

Floris
