### ISSUE TITLE
Can you share the input files for reproduce the figures?

### ISSUE THREAD

**Issue by zhaoliang0302** [TheJacksonLaboratory/GLASS#156]
Hi, thank you for sharing the codes of the figure visualization. These plots are so beautiful. I want to run these codes to understand them and try to apply them to my own research. However, I noticed that the input file in each R code was not provided, such as the ``con`` data frame in the ``F1-F3-GLASS-heatmap.R``. Can you kindly share the input files in the repository?
Thanks

**Comment by fpbarthel** [comment]
Hi @zhaoliang0302, thanks for the compliment! Unfortunately, the input data was pulled from a database and I no longer have direct access to this.

`con` is not a data frame but a pointer to a database connection. 
The script you are referring to uses various datasets for a number of distinct levels of data. The variables in the R script are called `xxxxdata`
The database connection `con` is used to query the database using an SQL scripts contained in this Github.

The essential data tables are largely contained on the Synapse page: https://www.synapse.org/#!Synapse:syn17038081

You can try taking your question to the discussion board: https://www.synapse.org/#!Synapse:syn17038081/discussion/default

You can also try generating the data frames your self using the SQL codes, but this is not going to be very straightforward.

**Comment by zhaoliang0302** [comment]
Thank you for you reply!
