### ISSUE TITLE
Can you share the code for reproduce the Extended Data Fig. 2A?

### ISSUE THREAD

**Issue by zhaoliang0302** [TheJacksonLaboratory/GLASS#157]
Dear Dr. Floris, 

I want to reproduce the Extended Data Fig. 2A. However, I noticed that the input file and the R code were not provided in `EDF2-fractionmf.R`. Can you kindly share them?

Thanks,
Liang

**Comment by fpbarthel** [comment]
Hi @zhaoliang0302.

The code for that figure can be found here: https://github.com/fpbarthel/GLASS/blob/333d5d01477e49bb2cf87be459d4161d4cde4483/R/snv/fig1-temporal-somatic-changes.R#L90-L101

Thanks @Kcjohnson for helping track that down.

For the input data, this can be generated from the tables on the Synapse page (https://www.synapse.org/glass). You could explore whether this data is also included in the legacy figure input data release that @Kcjohnson did some months ago: https://www.synapse.org/#!Synapse:syn26383767.

If not, you could either try to recreate it yourself, or post a question on the Synapse to request it.

Best of luck,
Floris
