### ISSUE TITLE
Structural variant calls?

### ISSUE THREAD

**Issue by sdalin** [TheJacksonLaboratory/GLASS#158]
Do structural variant calls exist for the GLASS dataset? Is the WGS deep enough for good quality SV calls? If there are not SV calls, could an SV caller like SvABA be run on the BAMs? We would be happy to collaborate to do this.

**Comment by fpbarthel** [comment]
Hi @sdalin, I would suggest placing your question at the Synapse page: https://www.synapse.org/#!Synapse:syn17038081/discussion/default

This Github repository issue board is only for issues related to the code base.
